### PR TITLE
Enforce all JavaScript src files code coverage

### PR DESCRIPTION
**Pull request by mightyiam**

### CODE REVIEW

**Comment by mightyiam** [comment]
Obviously, before this, merge #62.

**Comment by mightyiam** [comment]
The idea with this PR is that it will wait until we have full code coverage and then we hit "Update branch" and the tests here should pass and then we can merge.

**Comment by mightyiam** [comment]
Blocked by #21.

**Comment by mightyiam** [comment]
As you can see, this depends also on #64.

**Comment by yarom82** [comment]
Coverage is not 100% (Branch?)
However CI build passes..

**Comment by mightyiam** [comment]
We have #117.

**Pull request merged**
